### ISSUE TITLE
Clarify Usage of generated Schema

### ISSUE THREAD

**Issue by vanthome** [entria/graphql-dataloader-boilerplate#13]
The `npm run update-schema` and the output location `/data/ ` is mentioned in README.md. There is no word however, what's the purpose of this. From reading it, I would assume that the generated files are needed to run the server, this seems not to be the case however.
Can you clarify what the generated files are even good for?

**Comment by sibelius** [comment]
That's a really nice question, thank you!

`updateSchema` is used to generate 2 files

`schema.graphql` - is a pretty format of your schema.

You could write your graphql schema using .graphql syntax and use a tool like [apollostack/graphql-tools](https://github.com/apollostack/graphql-tools) (https://github.com/apollostack/graphql-tools) to generate an executable schema providing the resolvers functions.

`schema.json` is used by Babel Relay Plugin to transpile `Relay.QL` queries in [code](https://github.com/sibelius/graphql-dataloader-boilerplate/blob/master/scripts/updateSchema.js#L20).

example of relay code using schema.json - https://github.com/sibelius/ExNavRelay/tree/master/data

It can also be used to improve developer experience for Relay when using this plugin: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

They are not needed to run the server

Feel free to send a PR improving README and the docs

you could also be interested in using [create-graphql](https://github.com/lucasbento/create-graphql), it is a tool to generate graphql boilerplate based on mongoose schemas, we would like to support more databases in the future

**Comment by lucasbento** [comment]
This should definitely go on the README.

The files on `./data` should be put on the client-side to be used by the library that you have to deal with GraphQL server, [this is an example](https://github.com/lucasbento/react-relay-pokemon/blob/master/data/schema.json) with Relay so the [`babel-relay-plugin` can deal with them](https://github.com/lucasbento/react-relay-pokemon/blob/master/plugins/babelRelayPlugin.js#L3).

**Comment by vanthome** [comment]
Great stuff! many thanks, wasn't aware of the generator.
One question regarding "They are not needed to run the server".
Are you sure? As far I can see, none of the generated files are read?

I will try to create a PR based on this info.

**Comment by sibelius** [comment]
schema.json and schema.graphql is not needed to run the server

they are just used on client and on IDE plugins

remove schema.json and schema.graphql and try to run the server

**Comment by sibelius** [comment]
@vanthome can we close this?

**Comment by vanthome** [comment]
Jepp, it's clear now, closing it.
