### ISSUE TITLE
Use graphql` ` on tests

### ISSUE THREAD

**Issue by sibelius** [entria/graphql-dataloader-boilerplate#28]
![image](https://cloud.githubusercontent.com/assets/2005841/25252363/17c19d00-25f3-11e7-8804-1e92664f680d.png)

this provides great links highlight and code completion when using this plugin: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

**Comment by JCMais** [comment]
You can also add inject the language with a comment, and highlight and code completion will work:

```javascript
    //language=GraphQL
    const query = `
        mutation M( $text: String! ) {
            AddTodo(input: {
                clientMutationId: "1"
                text: $text
            }) {
                clientMutationId
                todoEdge {
                    node {
                        text
                    }
                }
                error
            }
        }`
```

**Comment by sibelius** [comment]
//language=GraphQL

works great

tks

**Comment by sibelius** [comment]
let's add this to all tests of this boilerplate
