### ISSUE TITLE
remove babel integration

### ISSUE THREAD

**Issue by phra** [entria/graphql-dataloader-boilerplate#36]
hi,

i think that you can safely remove babel integration because the latest version of node has everything we need. (notably native async/await)

EDIT: i see that you use babel for flow annotations.. at least we should remove the es2015 preset.

**Comment by sibelius** [comment]
we use Node 6 LTS here (https://github.com/entria/graphql-dataloader-boilerplate/blob/master/.nvmrc)

and we would like to use some features from stage-0 as well

**Comment by sibelius** [comment]
I think we use instead of `babel-preset-env` to transpile less code

I'm using this `.babelrc` config for Node 8

```jsx
{
  "presets": [
    "flow",
    ["env", {
      "targets": {
        "node": "current"
      }
    }],
  ],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-export-extensions"
  ]
}
```

**Comment by phra** [comment]
in my case i use typescript with es2017 as target so i get some transpilation/polyfill for free without using babel. (such as object rest/spread operators)

**Comment by sibelius** [comment]
it is never free, typescript does almost the same process of `babel`

we can have another repo to support typescript users, what do you think?

do you feel helping us doing that?

**Comment by phra** [comment]
i can definitely help for the boilerplate in typescript, but atm i still have to learn how dataloader works and how to use it.

**Comment by sibelius** [comment]
this could help: https://github.com/entria/swaggerGraphQLMocked/blob/master/.babelrc

**Comment by sibelius** [comment]
I'm gonna close this for now

babel is still useful for a lot of things like flow for us
