### ISSUE TITLE
Mutations naming convention 

### ISSUE THREAD

**Issue by eladams** [entria/graphql-dataloader-boilerplate#40]
I'm wondering if RegisterEmail should not be named RegisterEmailMutation or the other way around :)
What do you think?

**Comment by JCMais** [comment]
Yes, you are correct! The mutation is wrongly named.

**Comment by eladams** [comment]
It gets me wondering.. mutations are in the mutation[s] folder, why not to remove the `Mutation` suffix from all of them similarly to a components folder in a typical React project where you generally would not name your components with a `Component` suffix.

**Comment by sibelius** [comment]
could you send a PR to address this?
