### ISSUE TITLE
remove Viewer

### ISSUE THREAD

**Issue by sibelius** [entria/graphql-dataloader-boilerplate#46]
Viewer is not needed for Relay Modern or Apollo

I think we can remove it now

reference issues:
- https://github.com/lucasbento/graphql-pokemon/issues/1
- https://github.com/relayjs/relay-examples/issues/14
- https://github.com/nuwave/lighthouse/issues/15

Relay Modern reference commit: https://github.com/wincent/masochist/commit/637d0184f3318370b9ebc5285535e49

**Comment by JCMais** [comment]
cc @felippepuhle

**Comment by jgcmarins** [comment]
@augustolazaro
https://github.com/entria/graphql-boilerplate/pull/2

**Comment by ssomnoremac** [comment]
@sibelius just so I know I'm on the same page as you on this, removing `viewer` also removes the concept of `me`. So it would be just `result.data.users` in `UserType.sepc.js` for instance.

**Comment by sibelius** [comment]
no, `me` is still a thing

- `me` field is just a `UserType`, the logged user

`me: (_, args, context) => context.user`

**Comment by sibelius** [comment]
fix by this https://github.com/entria/graphql-dataloader-boilerplate/pull/59

**Comment by idkjs** [comment]
Link is dead:
"me: (_, args, context) => context.user check this https://github.com/entria/graphql-dataloader-boilerplate/blob/master/src/type/ViewerType.js#L27'

**Comment by sibelius** [comment]
the link is broken, because there is no viewer

**Comment by idkjs** [comment]
Just trying to read the history to understand the discussion that led up to no viewer...
