### ISSUE TITLE
[Question] What makes userId a string and not an ObjectId [ViewerLoader.js]?

### ISSUE THREAD

**Issue by eladams** [entria/graphql-dataloader-boilerplate#48]
```javascript
// @flow

type ViewerType = {
  id: ?string,
}

export default class Viewer {
  id: ?string;

  constructor(data: ViewerType) {
    this.id = data.id;
  }
};

export const load = (userId: string): Viewer => {
  const data = {
    id: userId,
  };

  return new Viewer(data);
};

// There is no need for a DataLoader instance here.
export const getLoader = () => Viewer;

```
ViewerLoader.js is called from QueryType.js

```javascript
resolve: async (obj, args, { user }) =>
         await ViewerLoader.load(user ? user._id : null)
      ,
```

I'm wondering what makes it work without flow errors, I thought it should be `user.id` (virtual mongoose getter: `id: () => obj._id.toString()`

**Comment by sibelius** [comment]
it is an ObjectId in fact, we should use userId.toString()

this code will disappear when we remove Viewer https://github.com/entria/graphql-dataloader-boilerplate/issues/46

**Comment by sibelius** [comment]
no viewer anymore \o/

https://github.com/entria/graphql-dataloader-boilerplate/pull/59

**Comment by idkjs** [comment]
Seems like this requires someone to login. What if you have some data that doesnt require someone to login?

**Comment by sibelius** [comment]
there is no need for Viewer anymore,

You can add some fields on QueryType, much like in Viewer

you can control what the user can see, using the viewerCanSee pattern

https://medium.com/entria/how-to-implement-viewercansee-in-graphql-78cc48de7464
