### ISSUE TITLE
setup lint-staged with prettier

### ISSUE THREAD

**Issue by sibelius** [entria/graphql-dataloader-boilerplate#50]
![image](https://user-images.githubusercontent.com/2005841/27699146-b043f07e-5ccf-11e7-94e7-9f87108719ca.png)

**Comment by vcapretz** [comment]
going to use `eslint-plugin-prettier` here, so prettier will be integrated with eslint and we won't need to specify the rules on package.json file, what do you think? cc @sibelius

**Comment by jgcmarins** [comment]
We add a pre-commit line at package.json, so it will run prettier before commit.

**Comment by vcapretz** [comment]
there's a package for inserting pre-commit but I did it directly under the key "scripts" on package.json, so the dependency would not be necessary :smiley:

**Comment by jgcmarins** [comment]
But it runs automatically?

**Comment by vcapretz** [comment]
Actually `husky` is responsible for this, it also supports "prepush" command

**Comment by jgcmarins** [comment]
Nice!
So if @sibelius approves, you can merge it :smile:
