### ISSUE TITLE
Improve parallel tests

### ISSUE THREAD

**Issue by ronal2do** [entria/graphql-dataloader-boilerplate#69]
Spinning up mongod in memory for fast tests. If you run tests in parallel this lib helps to spin up dedicated mongodb servers for every test file run.

https://github.com/nodkz/mongodb-memory-server

**Comment by eldad87** [comment]
Consider using an in-memory storage which you can mount Mongo's data to:
https://docs.docker.com/registry/storage-drivers/inmemory/
