### ISSUE TITLE
Implement subscriptions

### ISSUE THREAD

**Issue by ronal2do** [entria/graphql-dataloader-boilerplate#72]
https://github.com/entria/graphql-dataloader-boilerplate/tree/feature/subscriptions

**Comment by ronal2do** [comment]
benchmark
https://github.com/janie128/subscription-graphql

**Comment by ronal2do** [comment]
https://dev-blog.apollodata.com/how-to-use-subscriptions-in-graphiql-1d6ab8dbd74b

**Comment by jgcmarins** [comment]
https://github.com/entria/graphql-dataloader-boilerplate/pull/73
